<a href="https://colab.research.google.com/github/mickeykim70/DL_scratch/blob/main/gradient_simplenet_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import sys, os
import numpy as np
sys.path.append("/content/drive/MyDrive/deep-learning-from-scratch-master")

In [14]:
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [15]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3)

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [16]:
x = np.array([0.6, 0.9])
t = np.array([0.0, 0.0, 1.0])

In [17]:
net = simpleNet()

In [18]:
f = lambda w: net.loss(x, t)
dW = numerical_gradient(f, net.W)

print(dW)

[[ 0.22601992  0.33032042 -0.55634034]
 [ 0.33902988  0.49548063 -0.83451051]]


In [20]:
for i in range(5):
    print(net.W)
    print(softmax(net.predict(x)))
    print(net.loss(x,t))
    net.W -= dW

[[ 0.07409306  0.53323779 -1.44560066]
 [-0.10434727  0.01115625 -0.91812643]]
[0.37670039 0.55053479 0.07276483]
2.620521237861863
[[-0.15192686  0.20291737 -0.88926032]
 [-0.44337715 -0.48432438 -0.08361592]]
[0.32460659 0.38709417 0.28829925]
1.2437559451315119
[[-0.37794678 -0.12740305 -0.33291997]
 [-0.78240703 -0.97980501  0.75089459]]
[0.16510714 0.16065555 0.67423731]
0.3941729940975366
[[-0.60396671 -0.45772347  0.22342037]
 [-1.12143692 -1.47528563  1.5854051 ]]
[0.0486141  0.03859782 0.91278808]
0.09125143239294618
[[-0.82998663 -0.78804389  0.77976071]
 [-1.4604668  -1.97076626  2.41991561]]
[0.01136633 0.00736362 0.98127006]
0.01890746824235124
